/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals.cs;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Ryven
 */
public class AdminReg extends javax.swing.JFrame {

    /**
     * Creates new form AdminReg
     */
    
    Connection con = null;
    PreparedStatement statement = null;
    ResultSet result = null;

    public AdminReg() {
        initComponents();
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/csdb","root","");
        }catch(SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Registration");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setBackground(new java.awt.Color(255, 235, 201));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 770, 320, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 674, -1, -1));

        btnRegister.setBackground(new java.awt.Color(117, 52, 34));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 770, 320, 60));

        txtFirstname.setBackground(new java.awt.Color(255, 248, 232));
        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFirstname.setBorder(null);
        getContentPane().add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 300, 50));

        txtLastname.setBackground(new java.awt.Color(255, 248, 232));
        txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLastname.setBorder(null);
        getContentPane().add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 420, 300, 50));

        txtEmail.setBackground(new java.awt.Color(255, 248, 232));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEmail.setBorder(null);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 545, 660, 45));

        txtPassword.setBackground(new java.awt.Color(255, 248, 232));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setMinimumSize(new java.awt.Dimension(96, 34));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 670, 670, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/Admin Registration.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String fname, lname, email, password;
        
        fname = txtFirstname.getText();
        lname = txtLastname.getText();
        email = txtEmail.getText();
        password = txtPassword.getText();

        try{
                String query = "INSERT INTO `admin_account`(`first_name`, `last_name`, `email`, `password`) VALUES ('"+fname+"','"+lname+"','"+email+"','"+password+"')";
                statement = con.prepareStatement(query);
                statement.executeUpdate();
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }
        
        JOptionPane.showMessageDialog(this, "Registered Successfully","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
