/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals.cs;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;


/**
 *
 * @author Ryven
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   
        
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStudentLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnAdminLogin1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(117, 52, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        btnStudentLogin.setBackground(new java.awt.Color(255, 182, 85));
        btnStudentLogin.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        btnStudentLogin.setText("Login as a Student");
        btnStudentLogin.setBorderPainted(false);
        btnStudentLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentLogin);
        btnStudentLogin.setBounds(1310, 450, 350, 80);

        btnRegister.setBackground(new java.awt.Color(214, 122, 0));
        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(1310, 650, 350, 80);

        btnAdminLogin1.setBackground(new java.awt.Color(255, 182, 85));
        btnAdminLogin1.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        btnAdminLogin1.setText("Login as an Admin");
        btnAdminLogin1.setBorderPainted(false);
        btnAdminLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminLogin1);
        btnAdminLogin1.setBounds(1310, 550, 350, 80);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/log in bg.png"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLoginActionPerformed
        new StudentLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudentLoginActionPerformed

    private void btnAdminLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLogin1ActionPerformed
        new AdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAdminLogin1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnStudentLogin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
