/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals.cs;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.*;  
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Ryven
 */
public class StudentLogin extends javax.swing.JFrame  {

    
    Connection con = null;
    PreparedStatement statement = null;
    ResultSet result = null;

    /**
     * Creates new form StudentLogin
     */
    
    
    
    public StudentLogin() {
        initComponents();
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/csdb","root","");
        }catch(SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentnumber = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnUserLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Login");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStudentnumber.setBackground(new java.awt.Color(255, 248, 232));
        txtStudentnumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtStudentnumber.setToolTipText("Email");
        txtStudentnumber.setBorder(null);
        getContentPane().add(txtStudentnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 390, 450, 73));

        txtPassword.setBackground(new java.awt.Color(255, 248, 232));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPassword.setToolTipText("Password");
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 600, 450, 80));

        btnUserLogin.setBackground(new java.awt.Color(255, 182, 85));
        btnUserLogin.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        btnUserLogin.setText("Login as user");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 720, 470, 73));

        btnCancel.setBackground(new java.awt.Color(117, 52, 34));
        btnCancel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 810, 470, 73));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/user login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        PreparedStatement ps;
        ResultSet rs;

        String student_number = txtStudentnumber.getText();
        String Password = String.valueOf(txtPassword.getPassword());

        String query = "SELECT * FROM `student_account` WHERE `student_number` =? AND `password` =?";
        
        
        try{

            ps = con.prepareStatement(query);

            ps.setString(1, student_number);
            ps.setString(2, Password);

            rs = ps.executeQuery();

            if (rs.next()) {
               new UserPanel(student_number).setVisible(true);
               this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Credentials","INFORMATION",JOptionPane.ERROR_MESSAGE);
            }

        } catch(SQLException sqlException) {
            sqlException.printStackTrace();
        }

    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtStudentnumber;
    // End of variables declaration//GEN-END:variables
}
