/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals.cs;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Ryven
 */

public class UserReg extends javax.swing.JFrame {

    /**
     * Creates new form UserReg
     */
    
    Connection con = null;
    PreparedStatement statement = null;
    ResultSet result = null;
    
    
    public UserReg() {
        initComponents();
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/csdb","root","");
        }catch(SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtStudentnumber = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 235, 201));
        btnBack.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 825, 320, 60));

        txtFirstname.setBackground(new java.awt.Color(255, 248, 232));
        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFirstname.setBorder(null);
        txtFirstname.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 360, 300, 40));

        txtLastname.setBackground(new java.awt.Color(255, 248, 232));
        txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLastname.setBorder(null);
        getContentPane().add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 360, 300, 40));

        txtEmail.setBackground(new java.awt.Color(255, 248, 232));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEmail.setBorder(null);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 480, 670, 50));

        txtPassword.setBackground(new java.awt.Color(255, 248, 232));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 605, 670, 50));

        txtStudentnumber.setBackground(new java.awt.Color(255, 248, 232));
        txtStudentnumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtStudentnumber.setBorder(null);
        getContentPane().add(txtStudentnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 730, 670, 50));

        btnRegister.setBackground(new java.awt.Color(117, 52, 34));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 825, 320, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_components/User Registration.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String fname, lname, email, password, snumber;
        
        fname = txtFirstname.getText();
        lname = txtLastname.getText();
        email = txtEmail.getText();
        password = txtPassword.getText();
        snumber = txtStudentnumber.getText();

        try{
                String query = "INSERT INTO `student_account`(`first_name`, `last_name`, `email`, `password`, `student_number`) VALUES ('"+fname+"','"+lname+"','"+email+"','"+password+"','"+snumber+"')";
                statement = con.prepareStatement(query);
                statement.executeUpdate();
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }
        
        String query = "CREATE TABLE "+snumber+" (title varchar(255), author varchar(255), category varchar(255), pages varchar(255), ISBN varchar(255), borrow_date varchar(255), due_date varchar(255), borrowerId varchar(255))";
        try {
            statement = con.prepareStatement(query);
        } catch (SQLException ex) {
            Logger.getLogger(UserReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(UserReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Registered Successfully","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtStudentnumber;
    // End of variables declaration//GEN-END:variables
}
